### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by SamuelBroughton** [alex742/Calculator#1]
Hi, I needed to do the operation 18+19 but got "invalid operation". I'm wondering if/when this functionality will come available?

Cheers for the great work, keep it up!

**Comment by alex742** [comment]
Hi Samuel,

Firstly I just want to say thank you for commenting on my repository, I've never even spoken to someone with 45+ stars before!

I'll try and expand the functionality of the calculator tonight, thank you for your patience!

**Comment by SamuelBroughton** [comment]
Cheers for the update, much appreciated!
